CREATE DATABASE KandF_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'KandF_db_user'@'127.0.0.1' IDENTIFIED BY 'q.7xY49oySjiujHrbIIXfE4JQiJNLsHRr:';
GRANT ALL PRIVILEGES ON KandF_db.* TO 'KandF_db_user'@'127.0.0.1';
FLUSH PRIVILEGES;
EXIT;